-- CreateTable
CREATE TABLE "system_settings" (
    "id" TEXT NOT NULL,
    "systemName" TEXT NOT NULL DEFAULT 'Infrastructure Monitoring System',
    "systemSubtitle" TEXT NOT NULL DEFAULT 'Project Management Platform',
    "organizationName" TEXT NOT NULL DEFAULT 'Your Organization',
    "organizationSubtitle" TEXT NOT NULL DEFAULT 'Infrastructure Department',
    "loginTitle" TEXT NOT NULL DEFAULT 'Secure Access Portal',
    "loginDescription" TEXT NOT NULL DEFAULT 'Authorized personnel only - Enter your credentials to access the system',
    "loginFooterText" TEXT NOT NULL DEFAULT 'Contact administrator for account registration',
    "dashboardWelcomeTitle" TEXT NOT NULL DEFAULT 'Welcome to the System',
    "dashboardWelcomeText" TEXT NOT NULL DEFAULT 'Select a project to start monitoring progress',
    "primaryColor" TEXT NOT NULL DEFAULT '#3B82F6',
    "secondaryColor" TEXT NOT NULL DEFAULT '#10B981',
    "accentColor" TEXT NOT NULL DEFAULT '#F59E0B',
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "currencyCode" TEXT NOT NULL DEFAULT 'USD',
    "currencySymbol" TEXT NOT NULL DEFAULT '$',
    "dateFormat" TEXT NOT NULL DEFAULT 'MM/dd/yyyy',
    "timeZone" TEXT NOT NULL DEFAULT 'UTC',
    "enableGpsTracking" BOOLEAN NOT NULL DEFAULT true,
    "enableContractors" BOOLEAN NOT NULL DEFAULT true,
    "enableFinancials" BOOLEAN NOT NULL DEFAULT true,
    "enableReports" BOOLEAN NOT NULL DEFAULT true,
    "supportEmail" TEXT,
    "supportPhone" TEXT,
    "isSetupComplete" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);
